export const CREATE_USER="CREATE_USER"
export const CREATE_SUCCESS="CREATE_SUCCESS"

export const UPDATE_USER="UPDATE_USER"
export const UPDATE_SUCCESS="UPDATE_SUCCESS"

export const DELETE_USER="DELETE_USER"
export const DELETE_SUCCESS="DELETE_SUCCESS"

export const FETCH_ID_USER="FETCH_ID_USER"
export const FETCH_ID_SUCCESS="FETCH_ID_SUCCESS"

export const FETCH_USER="FETCH_USER"
export const FETCH_SUCCESS="FETCH_SUCCESS"
